source :rubygems
gem 'sinatra'
gem 'sinatra-contrib'

gem 'rspec'
gem 'rack-test'

gem 'mongo_mapper'
gem 'machinist_mongo', :require => 'machinist/mongo_mapper'
gem 'bson_ext'

gem 'i18n'

gem 'rake'
