# Generated by cucumber-sinatra. (2012-03-01 21:40:29 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'chaoschat.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ChaosChat

class ChaosChatWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChaosChatWorld.new
end
